### ISSUE TITLE
Migrate mailing lists off mailman

### ISSUE THREAD

**Issue by mbbroberg** [basho-labs/the-basho-community#63]
We run a number of mailing lists on an aging platform known as mailman. After one too many inconveniences from the platform, we're considering moving it. 

What I assume we would migrate (are all visible here)[http://lists.basho.com/mailman/listinfo/]: 
- rebar
- riak-core
- riak-critical-issues
- riak-users-jp
- riak-users

What we could also migrate: 
- [webmachine](http://lists.therestfulway.com/mailman/listinfo/)

I expect we'd want to migrate to Google Groups given its prevalence. 

There are concerns of existing links, migrating that data, migrating the addresses and probably more. Who wants to jump in and discuss?

**Comment by jonmeredith** [comment]
The previous concern about it was that Google Groups (may?) require an account with Google to participate rather than just an email address. It may be ubiquitous enough that people don't care.
