### ISSUE TITLE
Document preferred branching and naming convention on repos

### ISSUE THREAD

**Issue by mbbroberg** [basho-labs/the-basho-community#74]
I'd like to make it quick and easy for people to figure out how to contribute to Basho Labs. These two topics come to mind. 

In regards to branching: I'm in full support of [the `git flow` methodology](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/).

For naming contention, I've discussed the following with peers at Basho: 

**FOCUS dash PRODUCT dash DESCRIPTOR dash NEED** with the latter two being option.

Examples: 
- spark-bdp-stockticker-demo 
- mesos-riak-vagrant
- ansible-riak

Why? It's nice to quickly see what is there and why it exists. 

Excuse the pedantic goal here.

**Comment by DeadZen** [comment]
Nothing pedantic about it at all, whatever makes it easier to to pull
upstream changes,
if that's following a simple convention at Basho, most of which is similar
to git flow develop/bug//feature branches, then that's a great goal.

To really be pedantic, I'll submit that there is a naming convention but
probably no naming contention ;p

**Comment by mjbrender** [comment]
Hey maintainers of other projects: how's this sound to you? We're talking just projects in Basho Labs to start. @basho-labs/chef-committers  @basho-labs/puppet-committers @basho-labs/ansible-committers @basho-labs/mesos-committers et al.

**Comment by binarytemple** [comment]
+1 sounds like a good idea.

**Comment by mjbrender** [comment]
I'll aim to document this next week! Putting the timer on here.

**Comment by cheeseplus** [comment]
I'm actually more in the http://endoflineblog.com/gitflow-considered-harmful, moreover it actually makes things more confusing for the Chef community where git-flow is overkill for cookbooks and is incredibly rare. If anything I think this would make contributing unnecessarily complicated in this context.

As for the naming of the project I am less opposed as I've no particular love for `riak-chef-cookbook` as the repo name and in the Chef world it's only the metadata name is really important.

**Comment by mjbrender** [comment]
Thanks for the article @cheeseplus - I'll read up. I see a +1 for naming and a -1 for branching. 

On the topic of branches, my current concern is the absurd quantity of eternal branches on many of our projects. We have stale code everywhere and vague update strategies. Maybe we can take the considerations from the article + the good parts of flow and make something that makes sense.

**Comment by cheeseplus** [comment]
I'd also point out that I'm very specifically concerned about the cookbook and other cfg mgmt repos in general. We did git-flow back when Hector and I were still at Basho and it was infinitely more trouble than it was worth in the context of Chef.

Totally agree about stale code and vague updated strategies generally but for at least the cookbook those are not issues.

**Comment by haf** [comment]
-1 on gitflow, +1 on github flow (releasable master)

+1 on naming (but I don't care much, really)

**Comment by cheeseplus** [comment]
+1 on github flow with the caveat that for the Chef cookbook you do the merge to master before "deploy" as that means putting it on Supermarket

**Comment by mjbrender** [comment]
I had some reading up to do on github flow and, I have to say, I'm happy you threw it out there @cheeseplus. A legible history is quite important. Thanks for jumping in as well @haf. 

I'm working on documenting these recommendations and welcome others opening PRs.
