### ISSUE TITLE
Riak keeps crashing (though it does start up)

### ISSUE THREAD

**Issue by fgonzalezaguirre** [basho-labs/the-basho-community#77]
Hello,

We've noticed one particular node in our 5 node cluster keeps crashing soon after it start up. It does start up, riak-admin cluster status detects the whole cluster as UP, but the node soon crashes again. We believe this is making the whole cluster quite a bit slower.

This  is a new behaviour, the node had been operational for quite a while without any problems.

The heart of the error according to the logs seems to be:

2016-10-18 11:45:34.722 [error] <0.4100.0> scan_key_files: error function_clause @ [{riak_kv_bitcask_backend,key_transform_to_1,[<<>>],[{file,"src/riak_kv_bitcask_backend.erl"},{line,99}]},{bitcask,'-scan_key_files/5-fun-0-',7,[{file,"src/bitcask.erl"},{line,1188}]},{bitcask_fileops,fold_keys_int_loop,5,[{file,"src/bitcask_fileops.erl"},{line,595}]},{bitcask_fileops,fold_file_loop,8,[{file,"src/bitcask_fileops.erl"},{line,720}]},{bitcask_fileops,fold_keys_loop,4,[{file,"src/bitcask_fileops.erl"},{line,575}]},{bitcask,scan_key_files,5,[{file,"src/bitcask.erl"},{line,1196}]},{bitcask,init_keydir_scan_key_files,4,[{file,"src/bitcask.erl"},{line,1289}]},{bitcask,init_keydir,4,[{file,"src/bitcask.erl"},{line,1241}]}]

though we also spotted the following:

2016-10-18 11:45:45.706 [error] <0.208.0> File operation error: emfile. Target: /usr/lib/riak/lib/basho-patches. Function: list_dir. Process: riak_core_claimant.

I honestly have no clue how to make head or tails of the errors, so I've posted the logs hoping you guys can help us out (or should we just nuke the server and re-install everything?). 

[console.log.txt](https://github.com/basho-labs/the-basho-community/files/578904/console.log.txt)
[crash.log.txt](https://github.com/basho-labs/the-basho-community/files/578905/crash.log.txt)
[erlang.log.txt](https://github.com/basho-labs/the-basho-community/files/578907/erlang.log.txt)
[error.log.txt](https://github.com/basho-labs/the-basho-community/files/578908/error.log.txt)
[run_erl.log.txt](https://github.com/basho-labs/the-basho-community/files/578909/run_erl.log.txt)

**Comment by lukebakken** [comment]
`emfile` means that the file descriptor limit has been reached. Please see [this document](http://docs.basho.com/riak/kv/2.1.4/using/performance/open-files-limit/) to increase the open files limit on all of your servers.

Riak emits a warning on start if this limit is below `65536`. Do you see this warning?

**Comment by fgonzalezaguirre** [comment]
ulimit says "unlimited"

also have 
- soft nofile 65536
- hard nofile 65536

in /etc/security/limits.conf

Edit:

Few more things, ulimit -Hs prints unlimited, ulimit -Sn prints 65536

Also, cat /proc/riak_pid/limits prints the following:

scd@Xtrade135:~$ cat /proc/1563/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             515004               515004               processes
Max open files            1024                 4096                 files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       515004               515004               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

which for some reason means the ulimit isn't respected

**Comment by lukebakken** [comment]
Did you read the document I linked to?

Depending on your OS, you may have to edit other configuration files, like for PAM ([Debian/Ubuntu docs](http://docs.basho.com/riak/kv/2.1.4/using/performance/open-files-limit/#enable-pam-based-limits-for-debian-ubuntu)).

**Comment by fgonzalezaguirre** [comment]
Thanks luke! i think i got it. Ulimit should be set correctly now, also upgrading to 2.1.4 seemed to fix the issue on its own, but we also fixed the ulimit issue to be sure.

**Comment by lukebakken** [comment]
Great! Did you have to modify PAM settings?

**Comment by fgonzalezaguirre** [comment]
Yep! Also did the /etc/default/riak trick.

I suggest you guys add checking /proc/riak_pid/limits in the guide (or as a
troubleshooting measure) as I just learned that the value of ulimit vs the
max limit might differ.

On Nov 8, 2016 1:13 PM, "Luke Bakken" notifications@github.com wrote:

Great! Did you have to modify PAM settings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/basho-labs/the-basho-community/issues/77#issuecomment-259246414,
or mute the thread

**Comment by lukebakken** [comment]
Good suggestion.

Riak runs as the `riak` user so running the `ulimit` command generally doesn't print the actual limit.
